// flow-typed signature: 187805f47586f9cc18a45c1465fa1061
// flow-typed version: <<STUB>>/iso-639-1_v^2.0.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iso-639-1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iso-639-1' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iso-639-1/build/index' {
  declare module.exports: any;
}

declare module 'iso-639-1/src/data' {
  declare module.exports: any;
}

declare module 'iso-639-1/src/index' {
  declare module.exports: any;
}

declare module 'iso-639-1/test/test' {
  declare module.exports: any;
}

declare module 'iso-639-1/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iso-639-1/build/index.js' {
  declare module.exports: $Exports<'iso-639-1/build/index'>;
}
declare module 'iso-639-1/src/data.js' {
  declare module.exports: $Exports<'iso-639-1/src/data'>;
}
declare module 'iso-639-1/src/index.js' {
  declare module.exports: $Exports<'iso-639-1/src/index'>;
}
declare module 'iso-639-1/test/test.js' {
  declare module.exports: $Exports<'iso-639-1/test/test'>;
}
declare module 'iso-639-1/webpack.config.js' {
  declare module.exports: $Exports<'iso-639-1/webpack.config'>;
}
