// flow-typed signature: 5b6001806d22541eb016796c00aa5b94
// flow-typed version: <<STUB>>/re-reselect_v^3.1.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-reselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 're-reselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-reselect/dist/index' {
  declare module.exports: any;
}

declare module 're-reselect/es/index' {
  declare module.exports: any;
}

declare module 're-reselect/lib/index' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FifoMapCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FifoObjectCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FlatMapCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FlatObjectCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/LruMapCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/LruObjectCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/util/isStringOrNumber' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/util/validateCacheSize' {
  declare module.exports: any;
}

declare module 're-reselect/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-reselect/dist/index.js' {
  declare module.exports: $Exports<'re-reselect/dist/index'>;
}
declare module 're-reselect/es/index.js' {
  declare module.exports: $Exports<'re-reselect/es/index'>;
}
declare module 're-reselect/lib/index.js' {
  declare module.exports: $Exports<'re-reselect/lib/index'>;
}
declare module 're-reselect/src/cache/FifoMapCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FifoMapCache'>;
}
declare module 're-reselect/src/cache/FifoObjectCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FifoObjectCache'>;
}
declare module 're-reselect/src/cache/FlatMapCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FlatMapCache'>;
}
declare module 're-reselect/src/cache/FlatObjectCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FlatObjectCache'>;
}
declare module 're-reselect/src/cache/LruMapCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/LruMapCache'>;
}
declare module 're-reselect/src/cache/LruObjectCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/LruObjectCache'>;
}
declare module 're-reselect/src/cache/util/isStringOrNumber.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/util/isStringOrNumber'>;
}
declare module 're-reselect/src/cache/util/validateCacheSize.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/util/validateCacheSize'>;
}
declare module 're-reselect/src/index.js' {
  declare module.exports: $Exports<'re-reselect/src/index'>;
}
